### ISSUE TITLE
Official releases in mangadex not appear in the feed

### ISSUE THREAD

**Issue by Elchizen** [kindlyfire/mdrss-ts#2]
Hello,
I have successfully created rss feeds for mangas and groups, however I have not been able to create a "viable" feed for mangaplus group releases which are links to the publisher's site.

I have tried to create feeds with different parameters (examples below) but they don't have recent releases that we can see on mangadex.
q=group:4f1de6a2-f0c5-4ac5-bce5-02c7dbb67deb,tl:en
q=group:4f1de6a2-f0c5-4ac5-bce5-02c7dbb67deb,tl:fr
q=manga:9d9b04ad-9a83-49f4-8ae4-a9a3780fe9c0,tl:en
q=manga:9d9b04ad-9a83-49f4-8ae4-a9a3780fe9c0,tl:fr

**Comment by kindlyfire** [comment]
The scraper currently ignores chapters with external URLs because it fetches based on `publishAt`, which is the date that the content becomes available on MD. That makes it ignore chapters not viewable on MD.

I may change that in the future, though
