### ISSUE TITLE
missing chapters

### ISSUE THREAD

**Issue by Ribelio** [kindlyfire/mdrss-ts#6]
Missing chapters for https://mdrss.tijlvdb.me/feed?q=manga:5209fe10-4a14-403f-8837-2ccf8cced253,tl:en

Even without the translation filter it's showing only some Arabic translations

the API seems fine though: https://api.mangadex.org/manga/5209fe10-4a14-403f-8837-2ccf8cced253/aggregate?translatedLanguage[]=en

sorry to open an git issue just for this, perhaps a server would be more appropriate

edit: My intention is to have all chapters scraped in my feed so I could track my start and finish of the series, I'm not sure if the purpose of this tool is to only fetch new entries of ongoing works

**Comment by kindlyfire** [comment]
Yes, the feed just keeps a few months of historical data. It's meant to inform of new releases. I'd recommend an actual tool to track your reading progress, like Anilist or Kenmei.

And this is indeed the right place for any questions or bug reports 🙂
